config/routes.rb
Securecopper::Application.routes.draw do

  namespace :admin do 
  	resources :roles
    resources :groups, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :add_users
      end
    end
    resources :hospitals, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
    resources :titles, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
  	resources :users, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :change_password
      end
    end
    
    resources :messages, :only=>[:index, :create,:new] do
      collection do
	      get :list
 			  post :search_contact
 			  match :set_recepients
 		  	post :delete_selected  
      end      
      member do 
      	delete :destroy
      end
    end
    
    resources :expire_settings_messages, :only => [:update,:new]
    
    match '/messages/:id/attachments' => "messages#show_attachments", :as => "show_attachments"    
    match '/messages/attachements/:id/download' => "messages#send_attachemnt_file", :as => "download_attachment"
    match '/users/get-user-list/:act' => "users#user_list", :as => "get_user_list"
  end

  devise_for :users, :controllers => {:sessions => "session", :passwords => "passwords"}, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  match '/messages/between_user/:user_id.(:format)' => 'messages#messages_between_user', :as => "messages_between_user" 
  
   resources :messages do
     collection do
       post :delete_selected       
     end
   end

  match '/temp_file_uploads/destroy/:id' =>'temp_file_uploads#destroy', :as => :temp_file_remote_delete
  match '/temp_file_uploads/delete/:id'=>'temp_file_uploads#destroy_file' , :as => :temp_file_delete
  match '/hospitalchange' => "admin/hospitals#change_hospital"
  resources :temp_file_uploads
  root :to => "home#index"

  get '/users/search(.:format)' => "users#search"   
  resources :users, :only => :index

  namespace :api do
   get '/users/messages/lifespan/get' => "expire_settings_messages#show"
   post '/users/messages/lifespan/set' => "expire_settings_messages#update"
   match '/messages/between_user/:user_id' => "messages#messages_between_user"
  	resources :users, :only => [:index] do
  	  collection do 
  		  get 'search'
  		  post 'update_data'
  	  end
  	end
   resources :messages, :only => [:index,:show,:create,:destroy] 
   resources :groups, :only => [:index] do 
   	member do 
   		get 'group_users'
   		get 'hospital_groups_users'
   	end
   	collection do 
   		get 'hospital_groups'
   	end
   end
  end

end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  before_filter :check_valid_user

  def index
    @users_list = current_user.contact_list(current_user)
    @recepient_id = ""
  end

  def new
  	 @message = Message.new
  end  
  
  def create
    @users_list = current_user.contact_list(current_user)
    @message = Message.new()
    @message.body = params[:message][:body]
    @message.sender_id = current_user.id 
    @message.recepient_ids = params[:message][:recepient_ids].to_s.split(',')
    @message.expired_at = DateTime.now + current_user.expire_settings_message.lifespan_hours.to_i.hour if current_user.expire_settings_message.present? && current_user.expire_settings_message.expire_is_set?
    current_user.temp_file_uploads.find(:all,:conditions=>["keyname = ? and user_id=?",session[:session_id],current_user.id]).each{|tfile| 
     	@fileupload = Attachment.new
     	@fileupload.data = tfile.data
     	@message.attachments << @fileupload  if !@fileupload.data_file_name.nil? && @fileupload.save
    }
    logger.warn("---#{@message.valid?}---#{@message.errors.full_messages.inspect}-------------------------")  
    respond_to do |format|
      if @message.save
        flash[:notice] = "Message successfully created"
        TempFileUpload.destroy_all(:user_id => current_user.id,:keyname => session[:session_id])
        if params[:save_method] == "apply"
         format.html { redirect_to admin_messages_url, :layout => !request.xhr? }
         format.js 
        elsif params[:save_method] == "apply_new"
         format.html { redirect_to new_admin_message_url, :layout => !request.xhr? }
        else
	    	@recepient_id = @message.recepient_ids.first
  			@recepient = User.find(@recepient_id) if @recepient_id.present?
         format.html { redirect_to admin_messages_url, :layout => !request.xhr? }
         format.js 
        end
      else
        if params[:save_method] == "apply" || params[:save_method] == "apply_new" 
        		format.html { render :action => "new", :layout => !request.xhr? }
        		format.js
        else
        		format.html { render :action => "index", :layout => !request.xhr? }
        		format.js
        end		 
      end
     end
  end
  
  def list
    @recepient_id = params[:id].to_i
    #@messages = current_user.all_messages_for_user(@recepient_id)
    @messages = Message.messages_between_user(current_user.id,@recepient_id)
    @recepient = User.find(@recepient_id)
    respond_to do |format|
      format.html { render :partial=>"/admin/messages/message_list_by_user", :locals=>{:recepient_id => @recepient_id,:recepient => @recepient}}
      format.pdf { 
        pdf = MessageDocument.new(@messages,current_user,@recepient)
        send_data pdf.render, :filename => "message_between_#{current_user.first_name}_and_#{@recepient.first_name}.pdf",:type => "application/pdf",:disposition => "inline"      
      }
    end  
  end

  def search_contact
    if !params[:first_name].blank?
       @users_list = User.contact_list(current_user,["#{current_user.id}"]).where("first_name regexp '^#{params[:first_name]}'")
    else
       @users_list = User.contact_list(current_user,["#{current_user.id}"])
    end	
  end

  def set_recepients
    if request.get?
      @users_list = current_user.contact_list(current_user)
      render :layout => false 
    else
  	 	@recepients = User.find_all_by_id(params[:cid])
  	 end	
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find_by_id(id)
          @message.mark_deleted(current_user) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to admin_messages_path
    end
  end

  def show_attachments
  	 @message = Message.find(params[:id])
  	 @attachments = @message.attachments
  	 respond_to do |format|
  	 	format.js
  	 	format.html {render :partial => "show_attachments", :object => @attachments}
  	 end
  end

  def send_attachemnt_file
    @attchment = Attachment.find(params[:id])
    if @attchment.message.sender_id == current_user.id || @attchment.message.recepients.include?(current_user) 
  	 	send_file "#{@attchment.data.path}", :type => "#{@attchment.data_content_type}"
  	else
  	 	render :text => "You are not allowed to access this file.",:layout => "application"	
  	end
  end
  
  def destroy
	  @message = Message.find(params[:id])
	  if @message.present?
    	@message.mark_deleted(current_user)
    end
    respond_to do |format|
    	format.js 
    	format.html { redirect_to admin_messages_path }
    end 	
  end
   
  private
  def check_valid_user
    if !user_signed_in?
      flash[:error] = "You are not permitted, you have to log with user admin"
      redirect_to root_path
    end
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
   before_filter :authenticate_user!

   def index
  	 #@messages = Message.all_messages_for_user(current_user.id)
  	 @messages = Message.recent_message_list(current_user.id) 
  	 respond_to do |format|
     format.json{render :json => @messages.map{ |msg| r = msg.recepients.find(msg.recepient_id); {:id => msg.id,
                                                       :sender_first_name => msg.sender.first_name,
              	     																	 :sender_last_name => msg.sender.last_name,
               	     																	 :sender_title => msg.sender.title_name,
	                   																	 :sender_image => msg.sender.mini_photo_url,
                                                       :sender_email => msg.sender_email,
                                                       :attachmenats => msg.attachments.map{|atta|{:url => "#{atta.photo_url}"}},
                                                       :recepients=>[{:recepient_id => msg.recepient_id,
                                                       :recepient_email => r.email,
                                                       :recepient_image => r.mini_photo_url,
                                                       :recepient_first_name => r.first_name,
              	     																	 :recepient_last_name => r.last_name,
               	     																	 :recepient_title => r.title_name}],
               	     																	 :messages_count => msg.messages_count,
                                                       #:recepients => msg.message_recepients.map{|rec|{:recepient_id =>rec.recepient_id,:recepient_email => rec.recepient.email,
                                                       #:deleted => rec.recepient_deleted,:read_at => rec.read_at,:is_readed => rec.read?,:recepient_first_name => rec.recepient.first_name,
                                                       #:recepient_last_name => rec.recepient.last_name,:recepient_title => ((rec.recepient.title.present?)? rec.recepient.title.name : ''),:recepient_image => rec.recepient.mini_photo_url}},
                                                       :body => msg.body,:sender=>msg.sender_id,:expired_at => msg.formatted_expired_at,
                                                       :sender_deleted =>msg.sender_deleted, :expired =>msg.expired,:created_at => msg.formatted_created_at }}}
  	 end
   end

	def messages_between_user
		@messages = Message.messages_between_user(current_user.id,params[:user_id])
	  	 respond_to do |format|
	     format.json { render :json => @messages.map{|msg|{:sender_id => msg.sender_id,
	     																	 :sender_email => msg.sender_email,
	     																	 :sender_first_name => msg.sender_first_name,
	     																	 :sender_last_name => msg.sender_last_name,
	     																	 :sender_title => msg.sender_title,
	     																	 :sender_image => msg.sender.mini_photo_url,
	     																	 :recepient_first_name => msg.recepient_first_name,
	     																	 :recepient_last_name => msg.recepient_last_name,
	     																	 :recepient_title => msg.recepient_title,
	     																	 :recepient_image => User.find_by_id(msg.recepient_id).mini_photo_url, 
	     																	 :id => msg.id, 
	     																	 :recepient_id => msg.recepient_id,
	     																	 :body => msg.body,
	     																	 :recepient_email => msg.recepient_email,
	     																	 :created_at => msg.formatted_created_at,
	     																	 :is_readed => msg.mread_at.present?,
	     																	 :attachments_present => msg.attachment_present?,
	     																	 :attachmenats => msg.attachments.map{|atta|{:url => "#{atta.photo_url}"}},
	     																	 :expired_at => msg.formatted_expired_at}}.to_json}
	   end
	end  
  
  def show
    @message = Message.read(params[:id],current_user)
    respond_to do|format|
      format.json{render :json =>@message.to_json(:methods => [:sender_email,:attachment_urls,:sender_image_file],:include => {:message_recepients=>{:include => {:recepient=>{:only => :email}},:except=>[:message_id,:id]}})}
    end
  end

  def create
=begin
        @message = Message.new(params[:message])
        @message.sender = current_user
        if @message.valid?
          @message.expired_at = DateTime.now + current_user.expire_settings_message.lifespan_hours.to_i.hour if current_user.expire_settings_message.present? && current_user.expire_settings_message.expire_is_set?
    	   if !params[:attachments].blank? && !params[:attachments].nil?
        	 	unless params[:attachments].blank?
        	 		@attachments = (params[:attachments]).split(',')
        	  		@attachment_count = params[:attachments_count]
        	  		i = 1
    	      	@attachments.each do |attachment|
      	      	filename = "test#{Time.now.to_i}"
       					File.open("#{filename}_#{i}.png","wb") do |file|
      						temp2 = ActiveSupport::Base64.decode64(attachment)
      						file.write(temp2)
      						file.close
      		   		end 
      					f = File.open("#{filename}_#{i}.png")
      					itemphoto = @message.attachments.build
      					itemphoto.data = f
      					f.close
      					File.delete("#{filename}_#{i}.png")
      					i = i + 1
    				  end		
    			  end
    		 end	  
    		 if params[:video_attachments].present?
        	 	unless params[:video_attachments].blank?
        	 		@vattachments = (params[:video_attachments]).split(',')
        	  		i = 1
    	      	@vattachments.each do |attachment|
      	      	vfilename = "video#{Time.now.to_i}"
       					File.open("#{vfilename}_#{i}.mpeg","wb") do |file|
      						temp2 = ActiveSupport::Base64.decode64(attachment)
      						file.write(temp2)
      						file.close
      		   		end 
      					f = File.open("#{vfilename}_#{i}.mpeg")
      					itemphoto = @message.attachments.build
      					itemphoto.data = f
      					f.close
      					File.delete("#{vfilename}_#{i}.mpeg")
      					i = i + 1
    				 end		
    			  end
    		 end
         @message.save
         flash[:notice] = "Message sent!"
         respond_to do|format|
          format.json{render :json =>@message.to_json(:methods => [:sender_email,:attachment_urls,:sender_image_file],:include => {:message_recepients=>{:include => {:recepient=>{:only => :email}},:except=>[:message_id,:id]}})}
         end
        else
         flash[:notice] = "Invalid Message" 
          respond_to do |format|
    	      format.json{render :json => {:error => flash[:notice]}.to_json}
          end
        end
=end
      @message = Message.new
      @message.sender = current_user
      @message.body = params[:message_body]
      @message.recepient_tokens = params[:message_recepient_tokens]
      if params[:file].present? 
        @video_attachments = @message.attachments.build
        @video_attachments.data = params[:file]
      end   
     if @message.save
         flash[:notice] = "Message sent!"
         respond_to do|format|
          format.json{render :json =>@message.to_json(:methods => [:sender_email,:attachment_urls,:sender_image_file],:include => {:message_recepients=>{:include => {:recepient=>{:only => :email}},:except=>[:message_id,:id]}})}
         end
     else
       flash[:notice] = "Invalid Message" 
        respond_to do |format|
   	      format.json{render :json => {:error => flash[:notice]}.to_json}
        end
     end 
  end
  
  def destroy
  	@message = Message.find(params[:id])
  	if @message.present?
  		@message.mark_deleted(current_user) 
  		render :json => {:message => "message destroyed successfully!"}.to_json
  	else
  		render :json => {:error => "Message not exist!"}.to_json
  	end
  end

end

app/views/messages/_attachment.html.erb
<%#= javascript_include_tag "uploadify/swfobject","uploadify/jquery.uploadify.v2.1.4.js" %>
<%- session_key_name = Rails.application.config.session_options[:key] -%>
<style type="text/css">
* {margin:0px auto; padding:0;}
</style>
<!--<div style="position:absolute;position:relative\9;margin-left:285px;margin-top:678px;">-->
<div id="attachment_select" style="position:absolute;clear:both;position:relative\8;margin-left:200px;margin-top:10px;">
  <%= form_for TempFileUpload.new, :html => { :multipart => true,:id=>'new_temp_file_uplaod',:action=>'create',:method => 'post' } do |f| %>
    <%= f.hidden_field :keyname, :value => "#{session[:session_id]}" %>
    <div class="fileInputsforupload">
      <%= f.file_field :data,  :class => 'file' -%>
    <span id="loader" ><img src="/LoadingPanel.JS/LoadingIndicators/Loading_00.gif" alt="Loading..." /></span>
    </div>
  <% end %>
</div>


<script type="text/javascript" charset="utf-8">
  jQuery(document).ready(function() {
    jQuery('#temp_file_upload_data').click(function(event){
    event.preventDefault();
  });
  jQuery('#temp_file_upload_data').uploadify({
      'uploader'            : '/javascripts/uploadify/uploadify.swf',
      'script'              : '/temp_file_uploads',
      'multi'               : true,
      'auto'                :true,
      'queueID'             : 'custom-queue',
      'cancelImg'           : '/images/cancel.png', 
      'folder'              : '/system/temp_files',
      'queueSizeLimit'      : 10,
      'simUploadLimit'      : 10,
      'onError'             :function (event,ID,fileObj,errorObj) {
							    		  alert(errorObj.type + ' Error: ' + errorObj.info);
								     },
      'onInit'              : function(){jQuery('#loader').hide();},
      'sizeLimit'           : 900000000000,
      'scriptData'          : {'<%= session_key_name %>' : encodeURIComponent('<%= u cookies[session_key_name] %>'),
      'user_id'              : '<%= current_user.id %>',
      'keyname'              : '<%= session[:session_id]%>',
      'authenticity_token'  : encodeURIComponent('<%= u form_authenticity_token if protect_against_forgery? %>')
         },
      'onProgress': function() {showdiv(); }, 
      'onSelect': function(event, queueID, fileObj, reposnse, data) {
        jQuery('#temp_file_upload_data').uploadifyUpload();},
      'onSelectOnce': function(event, queueID, fileObj, reposnse, data) {
        jQuery('#temp_file_upload_data').uploadifyUpload();},
      'onCancel' : function(event, queueID, fileObj, reposnse, data) {
        jQuery.ajax({
        type: 'POST',
        url: '/temp_file_uploads/destroy/'+queueID,
         });
        jQuery('#temp_file_upload_data').uploadifyUpload();
       },
      'onComplete': function(event, queueID, fileObj, reponse, data) {
        jQuery("#uploadify_submit").ajaxSubmit({
        type: 'POST',
        dataType: 'xml',  // Tried to use json, but it's madness.  Don't do it.
        timeout: 10000,
        success: function(xml) {
        var response = jQuery(xml).find('response').first();
        if( jQuery(response).attr('msg') == 'success' ) {
        alert("Success");
        } else {
          alert('Error');
        }
        },
        error: function() {
          alert('ERROR!');
        }
        });
        },
      'onAllComplete'  : function(event,data) {
        jQuery.get('/temp_file_uploads', function(data) {
          jQuery('#save-queue').html(data);
        });
        hidediv(); 
        }
      });
  });
</script>

app/views/messages/_files_list.html.erb
        <!--<div id="custom-queue" style="float:right;"></div>-->
        <div id="save-queue" style="margin-left:20px;">
            <%= render :partial =>'/messages/temp_files' %>
        </div>

app/views/messages/_inbox.html.erb
<h2>Inbox</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if !message.read_at.nil? %>
					  <%= link_to h(truncate(message.body,:length => 15, :omission=>'..')), message_path(message) %>
					<% else %>
					  <%= link_to "#{h(truncate(message.body,:length => 15, :omission=>'..'))} (unread)", message_path(message) %>
					<% end %>
				</td>
				<td><%= h(message.sender.email) %><%#= link_to h(message.sender.email), admin_user_path(@user) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Outbox", messages_path(:mailbox => :sent)%> |
<%#= link_to "Readed Messages", messages_path(:mailbox => :readed)%> <!--|-->
<%= link_to "Compose", new_message_path%>

app/views/messages/_readed.html.erb
<h2>Readed Inbox</h2>
<table>
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					  <%= link_to "#{h(truncate(message.body,:length => 15, :omission=>'..'))}", message_path(message) %>
				</td>
				<td><%= h(message.sender.email) %><%#= link_to h(message.sender.email), admin_user_path(@user) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Sent", messages_path(:mailbox => :sent)%> |
<%= link_to "Inbox", messages_path%> |
<%= link_to "Compose", new_message_path%>

app/views/messages/_sent.html.erb
<h2>Sent</h2>
<table border=1>
	<tr>
		<th>Del?</th>
		<th>Subject</th>
		<!--<th>To</th>-->
		<th>Sent</th>
	</tr>
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(truncate(message.body,:length => 15, :omission=>'..')), message_path(message) %></td>
  			<!--<td><%#= link_to h(message.recipient.email), admin_user_path(@user) %></td>-->
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
 	<% end %>
</table>
<%= link_to "Inbox", messages_path %>

app/views/messages/_temp_files.html.erb
<% files_contents = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif','text/html','text/plain','application/pdf','application/xls','application/doc','application/msword','application/zip']%>
<% if current_user.temp_file_uploads.find(:all,:conditions=>["keyname= ?",session[:session_id]]) %>
  <% for temp_file in current_user.temp_file_uploads %>
    <div class="uploadifyQueueItem" style="margin-left:20px;">
      <div class="cancel"><%= link_to image_tag('/images/cancel.png'),:controller =>"temp_file_uploads", :action => 'destroy_file', :id => temp_file.id,:remote => true %></div>
      <!--<span class="fileName"><%= temp_file.data_file_name %>
      <%= temp_file.file_size.to_s  %></span>
      <span class="percentage"> - 100%</span>-->
      <% if files_contents.include?(temp_file.data_content_type)%>
        <span><%= image_tag("#{temp_file.data.url(:thumb)}") %></span>
      <% else %>
        <span><%= temp_file.data_file_name %></span>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/messages/index.html.erb
<%= form_tag delete_selected_messages_path(:method => :post) do %>
	<% if params[:mailbox] == "sent" %>
			<%= render :partial => "sent" %>
	<% elsif params[:mailbox] == "readed" %>
			<%= render :partial => "readed" %>
	<% else %>
			<%= render :partial => "inbox" %>
		<% end %>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message, :url => messages_path(@user) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :recepient_tokens, "Recepients" %><br />
    <%= f.text_field :recepient_tokens, "data-pre" => @message.recepients.map(&:attributes).to_json %>
  </p>
  <p>
    Message<br />
    <%= f.text_area :body,:style=>"height:90px;width:700px;" %>
  </p>
  <%= render :partial => "attachment"%>
  <br/><br/><br/><br/><br/>
  <%= render :partial =>'files_list' %>
  <br/>
  <%= f.submit "Create",:style=> "margin-top:20px;"%>
<% end %>

app/views/messages/show.html.erb
<p><strong>From:</strong> <%= (@message.sender == @user)?("you"):(@message.sender.email) %></p>
<p><strong>Created At:</strong> <%= @message.created_at.to_s(:long) %></p>
<p><strong>To:</strong> <%= @message.recepients.collect(&:email).join(',  ')  %></p>
<p>
  <strong>Message</strong><br />
  <%=h @message.body %>
</p>
<% if !@message.expired_at.nil?%>
<p>
  Expired At:<br/>
  <%= @message.expired_at %>
</p>
<%end%>

<p>
  <strong>Attachments</strong><br />
  <% i =0 %>
  <%for img in @message.attachments %>
    <% i = i+1 %>
    <%= image_tag(img.data.url(:thumb))%>
    <% if i%4 == 0%><br/><% end %>
  <% end %>
</p>

<p>
  <%= link_to "Inbox", messages_path%> |
  <%= link_to "Outbox", messages_path(:mailbox => :sent)%>
</p>