config/routes.rb
Securecopper::Application.routes.draw do

  namespace :admin do 
  	resources :roles
    resources :groups, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :add_users
      end
    end
    resources :hospitals, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
    resources :titles, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
  	resources :users, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :change_password
      end
    end
    
    resources :messages, :only=>[:index, :create,:new] do
      collection do
	      get :list
 			  post :search_contact
 			  match :set_recepients
 		  	post :delete_selected  
      end      
      member do 
      	delete :destroy
      end
    end
    
    resources :expire_settings_messages, :only => [:update,:new]
    
    match '/messages/:id/attachments' => "messages#show_attachments", :as => "show_attachments"    
    match '/messages/attachements/:id/download' => "messages#send_attachemnt_file", :as => "download_attachment"
    match '/users/get-user-list/:act' => "users#user_list", :as => "get_user_list"
  end

  devise_for :users, :controllers => {:sessions => "session", :passwords => "passwords"}, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  match '/messages/between_user/:user_id.(:format)' => 'messages#messages_between_user', :as => "messages_between_user" 
  
   resources :messages do
     collection do
       post :delete_selected       
     end
   end

  match '/temp_file_uploads/destroy/:id' =>'temp_file_uploads#destroy', :as => :temp_file_remote_delete
  match '/temp_file_uploads/delete/:id'=>'temp_file_uploads#destroy_file' , :as => :temp_file_delete
  match '/hospitalchange' => "admin/hospitals#change_hospital"
  resources :temp_file_uploads
  root :to => "home#index"

  get '/users/search(.:format)' => "users#search"   
  resources :users, :only => :index

  namespace :api do
   get '/users/messages/lifespan/get' => "expire_settings_messages#show"
   post '/users/messages/lifespan/set' => "expire_settings_messages#update"
   match '/messages/between_user/:user_id' => "messages#messages_between_user"
  	resources :users, :only => [:index] do
  	  collection do 
  		  get 'search'
  		  post 'update_data'
  	  end
  	end
   resources :messages, :only => [:index,:show,:create,:destroy] 
   resources :groups, :only => [:index] do 
   	member do 
   		get 'group_users'
   		get 'hospital_groups_users'
   	end
   	collection do 
   		get 'hospital_groups'
   	end
   end
  end

end

app/controllers/session_controller.rb
class SessionController < Devise::SessionsController

	def create
		if warden.authenticate?(:scope => resource_name)
			resource = warden.authenticate!(:scope => resource_name, :recall => "new")
			if resource.active?
	  			set_flash_message :notice, :signed_in
	  			sign_in(resource_name, resource)
	      	respond_to do|format|
		    		if resource.is_any_admin?
		    		 format.html{redirect_to  admin_users_path}
		          format.json{render :json => resource.to_json(:methods => [:mini_photo_url])}
		    		else
		          flash[:notice] = "Welcome to Secure Copper"
		          format.json{render :json => resource.to_json}
		    		 format.html{redirect_to admin_messages_path}
		    		end
	      	end
	      else
	      	flash[:error] = "Your account has been disabled by admin."
	      	sign_out(current_user)
	      	respond_to do |format|
	      	  format.html {redirect_to new_user_session_path}
	      	  format.json { render :json => {:error => "Your account has been disabled by admin!"}}
	      	end  
	      end	
    else
  		flash[:error] = "Invalid Email or Password"  
      respond_to do|format|  
		    format.html{redirect_to new_user_session_path}
        format.json{render :json => {:error => flash[:notice]}.to_json}
      end
    end	
	end
	
	def destroy
	   unless request.format.json?
			super
		else
			if current_user
				sign_out(current_user)
			end
			respond_to do |format|
				format.json { render :json => {:message => "successfully logout."}}
			end
		end	
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<div class="blackbar" style="padding: 15px;">
	<span class="calibri_16_gray"><b>Please sign in to continue</b></span>
</div>
<div class="contentsbar">
	<table cellspacing=0 cellpadding=0 width="900px;">
		<tr>
			<td width="274px;">
				<div class="login_bk">
					<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
					<div class="field">
				  		<span style="padding-bottom:5px;"><%= f.label :email %></span>
				  		<%= f.email_field :email, :class=>"input_text"  %>
					</div>
					<div class="field">
				  		<%= f.label :password %><br />
				  		<%= f.password_field :password, :class=>"input_text"  %>
					</div> 
					<div class="field">
				  		<button type="submit" class="bluebtn" id="login">Login</button>
					</div>  
					<div class="field">
						<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  							<%= link_to "Forgot your password?", new_password_path(resource_name) %>
						<% end -%>
					</div>
				<% end %>
			</div>
		  </td>
	   	<td width="600px;" class="login_video">	  	
				<iframe width="600" height="360" src="http://www.youtube.com/embed/eeu90xAEMB8" frameborder="0" allowfullscreen></iframe>
			</td>
	  </tr>
	</table>  			
</div>