config/routes.rb
Securecopper::Application.routes.draw do

  namespace :admin do 
  	resources :roles
    resources :groups, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :add_users
      end
    end
    resources :hospitals, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
    resources :titles, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
  	resources :users, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :change_password
      end
    end
    
    resources :messages, :only=>[:index, :create,:new] do
      collection do
	      get :list
 			  post :search_contact
 			  match :set_recepients
 		  	post :delete_selected  
      end      
      member do 
      	delete :destroy
      end
    end
    
    resources :expire_settings_messages, :only => [:update,:new]
    
    match '/messages/:id/attachments' => "messages#show_attachments", :as => "show_attachments"    
    match '/messages/attachements/:id/download' => "messages#send_attachemnt_file", :as => "download_attachment"
    match '/users/get-user-list/:act' => "users#user_list", :as => "get_user_list"
  end

  devise_for :users, :controllers => {:sessions => "session", :passwords => "passwords"}, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  match '/messages/between_user/:user_id.(:format)' => 'messages#messages_between_user', :as => "messages_between_user" 
  
   resources :messages do
     collection do
       post :delete_selected       
     end
   end

  match '/temp_file_uploads/destroy/:id' =>'temp_file_uploads#destroy', :as => :temp_file_remote_delete
  match '/temp_file_uploads/delete/:id'=>'temp_file_uploads#destroy_file' , :as => :temp_file_delete
  match '/hospitalchange' => "admin/hospitals#change_hospital"
  resources :temp_file_uploads
  root :to => "home#index"

  get '/users/search(.:format)' => "users#search"   
  resources :users, :only => :index

  namespace :api do
   get '/users/messages/lifespan/get' => "expire_settings_messages#show"
   post '/users/messages/lifespan/set' => "expire_settings_messages#update"
   match '/messages/between_user/:user_id' => "messages#messages_between_user"
  	resources :users, :only => [:index] do
  	  collection do 
  		  get 'search'
  		  post 'update_data'
  	  end
  	end
   resources :messages, :only => [:index,:show,:create,:destroy] 
   resources :groups, :only => [:index] do 
   	member do 
   		get 'group_users'
   		get 'hospital_groups_users'
   	end
   	collection do 
   		get 'hospital_groups'
   	end
   end
  end

end

app/models/admin/role.rb
class Admin::Role < ActiveRecord::Base
	has_many :users
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  # GET /admin/roles
  # GET /admin/roles.xml
  layout 'admin'
  def index
    @admin_roles = Admin::Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_roles }
    end
  end

  # GET /admin/roles/1
  # GET /admin/roles/1.xml
  def show
    @admin_role = Admin::Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_role }
    end
  end

  # GET /admin/roles/new
  # GET /admin/roles/new.xml
  def new
    @admin_role = Admin::Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_role }
    end
  end

  # GET /admin/roles/1/edit
  def edit
    @admin_role = Admin::Role.find(params[:id])
  end

  # POST /admin/roles
  # POST /admin/roles.xml
  def create
    @admin_role = Admin::Role.new(params[:admin_role])

    respond_to do |format|
      if @admin_role.save
        format.html { redirect_to(@admin_role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @admin_role, :status => :created, :location => @admin_role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/roles/1
  # PUT /admin/roles/1.xml
  def update
    @admin_role = Admin::Role.find(params[:id])

    respond_to do |format|
      if @admin_role.update_attributes(params[:admin_role])
        format.html { redirect_to(@admin_role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/roles/1
  # DELETE /admin/roles/1.xml
  def destroy
    @admin_role = Admin::Role.find(params[:id])
    @admin_role.destroy

    respond_to do |format|
      format.html { redirect_to(admin_roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<%= form_for(@admin_role) do |f| %>
  <% if @admin_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_role.errors.count, "error") %> prohibited this admin_role from being saved:</h2>

      <ul>
      <% @admin_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :role_name %><br />
    <%= f.text_field :role_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_role %> |
<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/index.html.erb
<h1>Listing Departments</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Role name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_roles.each do |admin_role| %>
  <tr>
    <td><%= admin_role.id %></td>
    <td><%= admin_role.role_name %></td>
    <td><%= link_to 'Show', admin_role %></td>
    <td><%= link_to 'Edit', edit_admin_role_path(admin_role) %></td>
    <td><%= link_to 'Destroy', admin_role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_admin_role_path %>

app/views/admin/roles/new.html.erb
<h1>New Department</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @admin_role.id %>
</p>

<p>
  <b>Role name:</b>
  <%= @admin_role.role_name %>
</p>


<%= link_to 'Edit', edit_admin_role_path(@admin_role) %> |
<%= link_to 'Back', admin_roles_path %>