config/routes.rb
Securecopper::Application.routes.draw do

  namespace :admin do 
  	resources :roles
    resources :groups, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :add_users
      end
    end
    resources :hospitals, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
    resources :titles, :except=>[:show,:destroy] do
      collection do
        post :allinone
      end
    end
  	resources :users, :except=>[:show,:destroy] do
      collection do
        post :allinone
        match :change_password
      end
    end
    
    resources :messages, :only=>[:index, :create,:new] do
      collection do
	      get :list
 			  post :search_contact
 			  match :set_recepients
 		  	post :delete_selected  
      end      
      member do 
      	delete :destroy
      end
    end
    
    resources :expire_settings_messages, :only => [:update,:new]
    
    match '/messages/:id/attachments' => "messages#show_attachments", :as => "show_attachments"    
    match '/messages/attachements/:id/download' => "messages#send_attachemnt_file", :as => "download_attachment"
    match '/users/get-user-list/:act' => "users#user_list", :as => "get_user_list"
  end

  devise_for :users, :controllers => {:sessions => "session", :passwords => "passwords"}, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  match '/messages/between_user/:user_id.(:format)' => 'messages#messages_between_user', :as => "messages_between_user" 
  
   resources :messages do
     collection do
       post :delete_selected       
     end
   end

  match '/temp_file_uploads/destroy/:id' =>'temp_file_uploads#destroy', :as => :temp_file_remote_delete
  match '/temp_file_uploads/delete/:id'=>'temp_file_uploads#destroy_file' , :as => :temp_file_delete
  match '/hospitalchange' => "admin/hospitals#change_hospital"
  resources :temp_file_uploads
  root :to => "home#index"

  get '/users/search(.:format)' => "users#search"   
  resources :users, :only => :index

  namespace :api do
   get '/users/messages/lifespan/get' => "expire_settings_messages#show"
   post '/users/messages/lifespan/set' => "expire_settings_messages#update"
   match '/messages/between_user/:user_id' => "messages#messages_between_user"
  	resources :users, :only => [:index] do
  	  collection do 
  		  get 'search'
  		  post 'update_data'
  	  end
  	end
   resources :messages, :only => [:index,:show,:create,:destroy] 
   resources :groups, :only => [:index] do 
   	member do 
   		get 'group_users'
   		get 'hospital_groups_users'
   	end
   	collection do 
   		get 'hospital_groups'
   	end
   end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :check_valid_user
  before_filter :set_page_and_per_page, :only => [:index]
  
  # GET /admin/users
  # GET /admin/users.xml
  def index
    @search_text = session[:search_users]
    (@search_text.blank?)?(@search_text=''):(@search_text='%'+@search_text+'%')
    if current_user.is_super_admin?
      @users = User.search_filter(@search_text).paginate(:page => @page,:per_page => @per_page,:order => "id asc")
    elsif current_user.is_hospital_admin?
      @users = User.search_filter(@search_text).paginate(:page => @page,:per_page => @per_page,:order=>"id asc", :conditions=>["hospital_id = ?", current_user.hospital_id])
    else
      @users = [current_user]
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
    unless current_user.is_super_admin?
      unless current_user.hospital_id.to_s ==  @user.hospital_id.to_s
        flash[:error] = "You are not permitted, you have to log with user admin"
        redirect_to root_path
      end
    end
  end

  # POST /admin/users
  # POST /admin/users.xml
  def create
    @user = User.new(params[:user])
    @user.deny_member_ids = params[:user][:deny_member_ids] if params[:user][:deny_member_ids].present? 
    respond_to do |format|
      if @user.save 
        #send mail notification to user.
        Mailer::Notifier.send_password_to_user(@user,params[:user][:password]).deliver
        if params[:user][:deny_member_ids].present?
        	 @deny_mem = @user.memberships.find_all_by_member_id(params[:user][:deny_member_ids])
        	 @deny_mem.each do |member|
        	 	member.update_attribute("allowed",false)
        	 end	
        end	 
        if params[:save_method] == "apply"
          format.html { redirect_to(admin_users_url, :notice => 'User was successfully created.') }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
        else
          format.html { redirect_to(new_admin_user_url, :notice => 'User was successfully created.') }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
        end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml
  def update
    @user = User.find(params[:id])
    if !params[:user][:allowed_member_ids].present?
    	@user.allowed_member_ids = []
	 end
    if !params[:user][:deny_member_ids].present?
    	@user.deny_member_ids = []
	 end
    respond_to do |format|
      if @user.update_attributes(params[:user])
        if params[:user][:deny_member_ids].present?
        	 @deny_mem = @user.memberships.find_all_by_member_id(params[:user][:deny_member_ids])
        	 @deny_mem.each do |member|
        	 	member.update_attribute("allowed",false)
        	 end	
        end
        if params[:save_method] == "apply"
          format.html { redirect_to(admin_users_url, :notice => 'User was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { redirect_to(new_admin_user_url, :notice => 'User was successfully created.') }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
        end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def allinone
    @source=params[:source]
    cid = []
    cid=params[:cid]
#    session[:limit_coupons]=params[:limit]
    if @source == 'edit'
      if cid
        @id=cid.first
        @user = User.find(@id)
        redirect_to(edit_admin_user_url(@user.to_param))
      else
        flash[:error] = 'You have not selected any record. Please try again.'
        redirect_to(admin_users_url)
      end
    elsif @source == 'delete'
      if cid
        User.destroy_all(['id in (?)',cid])
        redirect_to(admin_users_url)
      else
        flash[:error] = 'You have not selected any record. Please try again.'
        redirect_to(admin_users_url)
      end
    elsif @source == 'go'
      session[:search_users] = params[:filter_search]
      redirect_to(admin_users_url)
    elsif @source == 'reset'
      session[:search_users] = nil
      redirect_to(admin_users_url)
    elsif @source == 'activate'
    	cid = "#{cid.join(',')}" if cid.size > 1
    	@users = User.where("id in (#{cid})")
    	@users.each do |user|
			  user.update_attribute("status",1) 
    	end 
    	#User.update_all("status = 1","id in (#{cid})")
      if params[:page] == "1"
      	redirect_to(admin_users_url)
      else	
      	redirect_to(admin_users_url(:page => "#{params[:page]}"))
      end	
    elsif @source == 'block'
    	cid = "#{cid.join(',')}" if cid.size > 1
		  @users = User.where("id in (#{cid})")
   	  @users.each do |user|
    		user.update_attribute("status",0) if !user.is_any_admin? && user.id != current_user.id
    		if current_user.is_super_admin? && user.is_hospital_admin? 
    		  User.update_all("status = 0","hospital_id = #{user.hospital_id}")  
    		end
    	end 
      #User.update_all("status = 0","id in (#{cid})")
      if params[:page] == "1"
      	redirect_to(admin_users_url)
      else	
      	redirect_to(admin_users_url(:page => "#{params[:page]}"))
      end	
    else
      redirect_to(admin_users_url)
    end
  end
  
  def change_password
  		if request.get?
			@user = current_user  			
  		else
			@user = current_user  	
			if @user.update_with_password(params[:user])
				sign_in(@user, :bypass => true)
  				flash[:notice] = "Your password is changed successfully."
			else
  					
			end	
  		end
  end
  
  def user_list
    if request.get?
      hospital_id = params[:user][:hospital_id]
     	user_id = params[:user_id].present? ? params[:user_id] : ""
     	if hospital_id.present?
       	@groups = (!params[:user][:group_ids].present?)? "no-grp" : ((params[:user][:group_ids].size == 1 && params[:user][:group_ids].first == "")? "all_grp" : params[:user][:group_ids].join(','))
     		allowed_ids = params[:user][:allowed_member_ids].present? ? params[:user][:allowed_member_ids].join(',') : ""
	  	  deny_ids = (params[:user][:deny_member_ids].present?)? params[:user][:deny_member_ids].join(',') : ""
	     	if params[:act] == "allow_add"
	     		@users = allowed_user_list(@groups,user_id,hospital_id,allowed_ids)
	     	elsif params[:act] == "allow_remove"
	     		@users = get_users(allowed_ids)	
		  	elsif params[:act] == "deny_add"
		  	  @users =  deny_user_list(@groups,user_id,hospital_id,deny_ids)
		    elsif params[:act] == "deny_remove"
		      @users = get_users(deny_ids)
	    	end
				render :partial => "user_list", :locals => {:users => @users, :act => params[:act]}  
	    else
  	   	render :text => "You have to select hospital first."
	    end	
    else
      @act = params[:act]
     	@cid = params[:cid].join(",")
     	if params[:act] == "allow_add" || params[:act] == "deny_add"
     		@users = User.find(params[:cid])
     	elsif params[:act] == "allow_remove" || params[:act] == "deny_remove"
 				@cid = @cid.split(',')  					     		
    	end
   	  respond_to do |format|
   	   	format.js
   	  end 
   	end
  end

  private
  
  def check_valid_user
    if !user_signed_in?
      flash[:error] = "You are not permitted, you have to log with valid user"
      redirect_to root_path
    end
  end
  
  def allowed_user_list(groups,user_id,hospital_id,allowed_ids)
    except = merge_except_user(user_id,allowed_ids)
    if groups == "all_grp"
      @users = []
    elsif groups == "no-grp"
      @users =  User.active_hospital_users(hospital_id,except.split(','))
    else
		  @users = User.get_group_users(hospital_id,groups,except)
 		end
  end
  
  def deny_user_list(groups,user_id,hospital_id,deny_ids)
     except = merge_except_user(user_id,deny_ids)
 		 if groups == "all_grp"
 		   @users = User.active_hospital_users(hospital_id,except.split(','))
     elsif groups == "no-grp"
     	 @users = []
     else
		   @users = User.get_users_for_groups(groups,except)
		 end
  end

  def merge_except_user(user_id,member_ids)
     except = user_id 
     if except.blank?
       except = except + member_ids
     else
       except = except + "," + member_ids
     end     
  end
  
  def get_users(member_ids)
      if !member_ids.blank?
		    @users = User.find_all_by_id(member_ids.split(','))
		  else
		   	@users = []
		  end
  end   				
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	before_filter :authenticate_user!

	def index
	  @users = User.contact_list(current_user,["#{current_user.id}"])
	  response_parameters(@users)
	end
	
	def search
	  @users = User.contact_list(current_user,["#{current_user.id}"]).where("email like '%#{params[:q]}%'")
	  response_parameters(@users)
	end
	
	def update_data
    @users = current_user
    #@users.first_name = params[:user][:first_name] if params[:user][:first_name].present?
    #@users.last_name = params[:user][:last_name] if params[:user][:last_name].present?
    #@users.username = params[:user][:username] if params[:user][:username].present? 
    @users.device_type = params[:user][:device_type] if params[:user][:device_type].present?
    @users.device_registration_id = params[:user][:device_registration_id] if params[:user][:device_registration_id].present?
    if @users.save
     logger.warn("----d_reg_id:--#{@user.id}-:-#{@users.device_registration_id}----------------")
     respond_to do|format|
       format.json { render :json => @users.to_json(:except => [:encrypted_password,:parent_id,:created_at,
   	              :updated_at,:sign_in_count,:current_sign_in_at,:last_sign_in_at,:current_sign_in_ip,
   								:last_sign_in_ip,:user_creation_limit,:photo_file_name,:photo_content_type,:photo_file_size,
   							  :photo_updated_at],:methods => [:group_name,:role_name,:userid,:mini_photo_url,:title_name])
        }
     end 
    else
      respond_to do |format|
        format.json { render :json => @users.errors.full_messages.to_json }
      end
    end
	end 

   private

   def response_parameters(users)
     respond_to do|format|
       format.json { render :json => @users.to_json(:except => [:encrypted_password,:parent_id,:created_at,
     	              :updated_at,:sign_in_count,:current_sign_in_at,:last_sign_in_at,:current_sign_in_ip,
     								:last_sign_in_ip,:user_creation_limit,:photo_file_name,:photo_content_type,:photo_file_size,
     							  :photo_updated_at],:methods => [:group_name,:role_name,:userid,:mini_photo_url,:title_name])
      }
    end 
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate_user!
   
	def index
	 if current_user.is_super_admin? 
      @users = User.where("id != #{current_user.id}")
    elsif current_user.is_hospital_admin?
      @users = User.hospital_users(current_user.hospital_id).where("id != #{current_user.id}")
    else
      @users = User.group_users(current_user.primary_group_id,current_user.hospital_id).where("id != #{current_user.id}")
    end
	 respond_to do |format|
		  format.json { render :json => @users.to_json(:except => [:encrypted_password,:parent_id,:created_at,
     																			:updated_at,:sign_in_count,:current_sign_in_at,
     																			:last_sign_in_at,:current_sign_in_ip,
     																			:last_sign_in_ip,:user_creation_limit,
     																			:photo_file_name,:photo_content_type,:photo_file_size,
     																			:photo_updated_at],:methods => [:group_name,:role_name,:userid])
      }
    end  																			
	end
	
	def search
    if current_user.is_super_admin? 
      @users = User.where("email like ?","%#{params[:q]}%")
    elsif current_user.is_hospital_admin?
      @users = User.hospital_users(current_user.hospital_id).where("email like ?","%#{params[:q]}%")
    else
      @users = User.group_users(current_user.primary_group_id,current_user.hospital_id).where("email like ?","%#{params[:q]}%")
    end

    respond_to do|format|
      format.html 
      format.json{render :json => @users.map(&:attributes),:except =>[:encrypted_password]}
    end 
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_admin_only.html.erb
      <div class="field" id="group_form">
        <%= render :partial=>"/admin/users/group_form", :locals=>{:disabled=>disabled, :hospital_id=>hospital_id} %>
      </div>
      <div class="field" id="title_form">
        <%= render :partial=>"/admin/users/title_form", :locals=>{:disabled=>disabled, :hospital_id=>hospital_id} %>
      </div>
      <% unless hospital_id.blank? -%>
	      <div class="field" id="title_form">
	        <%= render :partial=>"/admin/users/group_membership", :locals=>{:disabled=>disabled, :hospital_id=>hospital_id} %>
	      </div>
	      <div class="field" id="allow_users">
			  <%= render :partial => "/admin/users/allow_user_membership" %> 	      	
	      </div>
	      <div class="field" id="deny_users">
	        <%= render :partial => "/admin/users/deny_user_membership" %>
	      </div>
      <% end -%>

app/views/admin/users/_allow_user_membership.html.erb
<span>&nbsp;</span><label style="min-width:135px;margin-top:10px;">Allow</label> <br/>
<%#= hidden_field_tag "user[allowed_member_ids]",""%>
<%= select_tag "user[allowed_member_ids][]", options_from_collection_for_select(@user.allowed_members, "id", "name",@user.allowed_member_ids), :multiple => true, :size => 10, :class=>"select_users", :style => "width:250px;margin-top:10px;" %>
<%= link_to "Add Users", "JavaScript:void(0);",:id => "allow-add-list",:class => "bluebtn",:style => "float:none;" %>
<%= link_to "Remove Users","JavaScript:void(0);",:id => "allow-remove-list",:class => "bluebtn",:style => "float:none;" %>

app/views/admin/users/_deny_user_membership.html.erb
<span>&nbsp;</span><label style="min-width:135px;margin-top:10px;">Deny</label> <br/>
<%= select_tag "user[deny_member_ids][]", options_from_collection_for_select(@user.deny_members, "id", "name",@user.deny_member_ids), :multiple => true, :size => 10, :class=>"select_users", :style => "width:250px;margin-top:10px;" %>
<%= link_to "Add Users", "JavaScript:void(0);",:id => "deny-add-list", :remote => true,:class => "bluebtn",:style => "float:none;" %>
<%= link_to "Remove Users","JavaScript:void(0);",:id => "deny-remove-list", :remote => true,:class => "bluebtn",:style => "float:none;" %>

app/views/admin/users/_group_form.html.erb
        <span class="star">*</span><%= label_tag :user_primary_group_id, "Primary Group" %>
        <%= collection_select :user, :primary_group_id, (hospital_id.blank?)?(Admin::Group.all):(Admin::Group.group_list(hospital_id)) ,:id,:name,{:prompt => true}, {:class=>"select_text", :disabled=>disabled} %>

app/views/admin/users/_group_membership.html.erb
        <span class="star">*</span><%= label_tag "user[group_ids][]", "Group Membership" %>
        <%= check_box_tag "user[group_ids][]", "", false, :id=>"user_group_ids_all" %>
        <%= label_tag :check_all, "Check All", :style=>"float:none;display:inline;width:200px;padding-top:0px;" %>
        <div style="float:left;width:750px;margin-top:10px;">
          <% Admin::Group.group_list(hospital_id).each do |group| %>
          <div style="float:left;width:200px;margin-right:100px;">
            <%= check_box_tag "user[group_ids][]", group.id, (@user.nil?)?(false):(@user.group_ids.include?(group.id)), :id=>"user_group_ids_#{group.id}" %>
            <%= label_tag group.name, group.name, :style=>"float:none;display:inline;width:200px;padding-top:0px;" %>
          </div>
          <% end -%>
        </div>

app/views/admin/users/_title_form.html.erb
        <span class="star">*</span><%= label_tag :user_title_id, "Title" %>
        <%= collection_select :user, :title_id, (hospital_id.blank?)?(Admin::Title.all):(Admin::Title.title_list(hospital_id)),:id,:name,{:prompt => true}, {:class=>"select_text", :disabled=>disabled} %>

app/views/admin/users/_user_list.html.erb
<div class="contentsbar">
  	<% if !users.empty? %>
  	<!--content bar-->
	<%= form_for :user, :url => admin_get_user_list_path(:act => act) , :remote => true do |f| %>
  	<table class="tablegray">
  	  <thead>
  			<tr>
  		    <th width="1%"><%= check_box_tag "checkall-toggle", "", false, :title=>"Check All" %></th>
  				<th class="left" width="10%">Name</th>
  				<th class="nowrap" width="10%">User Groups</th>
  				<th class="nowrap" width="15%">Role</th>
  				<th class="nowrap" width="15%">Email</th>
  			</tr>
  	  </thead>
  	  <tbody>
		<% users.each do |user| -%>
		<tr>
			<td class="center"><%= check_box_tag "cb#{user.id}", user.id, false, :title=>"Checkbox for #{user.name}", :name=>"cid[]" %></td>
			<td><%= user.name %><%= ", " + user.title.name unless user.title.nil? %></td>
			<td class="center"><%= user.primary_user_group.name unless user.primary_user_group.nil? %></td>
			<td class="center"><%= user.role.role_name unless user.role.nil? %></td>
			<td class="center"><%= user.email %></td>
		</tr>	
	<% end -%>
	<tr>
		<td colspan=5 align="right"><button type="submit" class="bluebtn" id="user_submit">Select Users</button></td>
	</tr>
	</tbody>	
	</table>
	<% end %>
	<% else %>
		<% if act == "allow_add" %>
			&nbsp;&nbsp;&nbsp;You have added allow groups, so you allowed all users. No more users are there which are not in your list.
		<% elsif act == "allow_remove" %>
			&nbsp;&nbsp;&nbsp;Your allow users list is empty!
		<% elsif act == "deny_add" %>
			&nbsp;&nbsp;&nbsp;No user is added to selected groups.!
		<% elsif act == "deny_remove" %>
			&nbsp;&nbsp;&nbsp;Your deny users list is empty!
		<% end %>
	<% end %>
</div>

app/views/admin/users/change_password.html.erb
<%= form_for(@user, :url => change_password_admin_users_path  , :html => { :method => :post }) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this new information from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
 <div id="element-box">
	  <div class="m">
	   	<div class="fltlft">
	  			<div class="field">
	  				 <span class="star">*</span><%= f.label :current_password, "Current password",:style => "min-width:173px;" %>
  	   			 <%= f.password_field :current_password, :class=>"input_text"  %>
  				</div>
	  			<div class="field">
	  				 <span class="star">*</span><%= f.label :password, "New password",:style => "min-width:173px;" %>
  	   			 <%= f.password_field :password, :class=>"input_text"  %>
  				</div>
  				<div class="field">
  					<span class="star">*</span><%= f.label :password_confirmation, "Confirm new password",:style => "min-width:173px;" %>
  					<%= f.password_field :password_confirmation, :class=>"input_text" %>
  				</div>
  				<div class="field">
  					<button type="submit" class="bluebtn" id="change_password">Change Password</button>
  				</div>
  			</div>
  		</div>
  	</div>			
<% end %>

app/views/admin/users/edit.html.erb
<%= render :partial=>"/common/edit_toolbar", 
  :locals=>{ 
    :title=>"User Manager: Edit User", :icon_class=>"icon-48-user", :model_name=>"admin_user"
  } %>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= form_tag  allinone_admin_users_path, :id => 'myform',:name => 'myform'  do |f| -%>
  <%= render :partial=>"/common/index_toolbar", 
    :locals=>{ 
      :title=>"User Manager: List", :icon_class=>"icon-48-user", :model_name=>"admin_user", 
      :allow_new=> current_user.is_any_admin?,
      :allow_edit=> true,:allow_activate=> current_user.is_any_admin?,:allow_block=> current_user.is_any_admin?,:allow_unblock=> current_user.is_any_admin?,
      :allow_delete=> current_user.is_any_admin?,:allow_sendmessage => false,:allow_settings => false
    } %>
  
  <%= render :partial=>"/common/blackbar", 
    :locals=>{ 
      :allow_search=> current_user.is_any_admin?, :search_text => session[:search_users]
    } %>
    
  <div class="contentsbar">
  	<!--content bar-->
  	<table class="tablegray">
  	  <thead>
  			<tr>
  		    <th width="1%"><%= check_box_tag "checkall-toggle", "", false, :title=>"Check All" %></th>
  				<th class="left">Name</th>
  				<th class="nowrap" width="10%">User Groups</th>
  				<th class="nowrap" width="15%">Role</th>
  				<% if current_user.is_any_admin? -%><th class="nowrap" width="5%">Enabled</th><% end -%>
  				<th class="nowrap" width="15%">Email</th>
          <th class="nowrap" width="16%">Last Visit Date</th>
  			</tr>
  	  </thead>
  	  <tbody>
  			<% @users.each do |user| %>
  		  <tr>
  		    <td class="center">
  		      <%= check_box_tag "cb#{user.id}", user.id, false, :title=>"Checkbox for #{user.name}", :name=>"cid[]" %>
  		    </td>
          <td><%= link_to "#{user.name}",edit_admin_user_path(user) %><%= ", " + user.title.name unless user.title.nil? %></td>
          <td class="center"><%= user.primary_user_group.name unless user.primary_user_group.nil? %></td>
          <td class="center"><%= user.role.role_name unless user.role.nil? %></td>
          <% if current_user.is_any_admin? %>
          <td class="center">
            <% if user.active? -%>
            	<%= image_tag "/images/tick.png" %>
            <% else %>
            	<%= image_tag "/images/disabled.png" %>
            <% end -%>
          </td>
          <% end -%>
          <td class="center"><%= user.email %></td>
          <td class="center"><%= user.last_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') unless user.last_sign_in_at.nil? %></td>
  		  </tr>
  		  <% end %>
  		</tbody>
  	</table>
  <!--content bar close-->			
  </div>
  <%= hidden_field_tag :source, "", :value=>"index" %>
  <%= hidden_field_tag :page, "", :value=>"#{@page}" %>
  <%= will_paginate @users if current_user.is_any_admin? %>
<% end -%>

app/views/admin/users/new.html.erb
<%= render :partial=>"/common/new_toolbar", 
  :locals=>{ 
    :title=>"User Manager: New User", :icon_class=>"icon-48-user", :model_name=>"admin_user"
  } %>
<%= render 'form' %>

app/views/admin/users/user_list.js.erb
$.colorbox.close();
<% if @act == "allow_add" %>
	<% @users.each do |user| %>
		$("#user_allowed_member_ids_").append('<option value="<%=user.id%>" selected=selected><%=user.name%></option>');
	<% end %>	
<% elsif @act == "allow_remove" %>
	<%= @cid.each do |oid| %>
		$("#user_allowed_member_ids_ option[value='<%=oid%>']").remove()
	<% end %>
<% elsif @act == "deny_add" %>
	<% @users.each do |user| %>
		$("#user_deny_member_ids_").append('<option value="<%=user.id%>" selected=selected><%=user.name%></option>');
	<% end %>
<% elsif @act == "deny_remove" %>
	<%= @cid.each do |oid| %>
		$("#user_deny_member_ids_ option[value='<%=oid%>']").remove()
	<% end %>	
<% end %>	